### ISSUE TITLE
Suggestion: configurable yarn or npm as package manager

### ISSUE THREAD

**Issue by lirantal** [lirantal/create-node-lib#10]
**Is your feature request related to a problem? Please describe.**
Right now the project defaults to an npm install of the scaffolded packages, allow a prompt for choosing yarn or npm

**Describe the solution you'd like**
Update to the Sao file is required as well as the templates

**Comment by alemagio** [comment]
Hi, I would like to take a look at this if no one else is working on it.

**Comment by lirantal** [comment]
Sure thing
